Add a way to asynchronously create containers
hobbit-project/core pull request #51
Opened 2019-06-04 10:45 UTC by denkv

2019-06-04 12:29 UTC, MichaelRoeder requested changes
It looks good but I think the response queue should be reused.

2019-06-04 12:29 UTC, MichaelRoeder commented on src/main/java/org/hobbit/core/components/AbstractCommandReceivingComponent.java
> -
Why are you not reusing the existing queue?

2019-06-04 12:29 UTC, MichaelRoeder commented on src/main/java/org/hobbit/core/components/AbstractCommandReceivingComponent.java
> +            String responseQueueName = cmdChannel.queueDeclare().getQueue();
Creating a new queue for each request could make the container creation more expensive :disappointed:

2019-06-11 11:21 UTC, denkv commented
Reworked to use the single queue for responses again.

2019-06-11 12:06 UTC, MichaelRoeder commented on src/main/java/org/hobbit/core/components/AbstractCommandReceivingComponent.java
> +            responseFutures = new HashMap<>();
Please create it directly at the beginning (where it is defined).

2019-06-11 12:06 UTC, MichaelRoeder commented on src/main/java/org/hobbit/core/components/AbstractCommandReceivingComponent.java
> +    @Deprecated
Please remove `@Deprecated` and add javadoc comments instead.

2019-06-11 12:06 UTC, MichaelRoeder commented on src/main/java/org/hobbit/core/components/AbstractCommandReceivingComponent.java
> +                    String key = properties.getCorrelationId();
Check if the correlation ID is set (should always be set but you never know :P)

2019-06-11 12:06 UTC, MichaelRoeder commented on src/main/java/org/hobbit/core/components/AbstractCommandReceivingComponent.java
> +        cmdThreadPool = Executors.newCachedThreadPool();
1. Add two constructors. `AbstractCommandReceivingComponent(boolean execCmdsInParallel)` and `AbstractCommandReceivingComponent() {this(false);}`
2. based on the flag, instantiate cmdThreadPool as cached thread pool or single thread pool.

2019-06-11 20:59 UTC, denkv commented
Added a workaround for working with PlatformController which does not use correlation IDs in responses.

2019-06-12 10:32 UTC, MichaelRoeder approved these changes
LGTM

2019-06-12 13:41 UTC, closed without merging